on:
  push:
    branches:
      - main

jobs:
  
  osv-scanner:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - uses: actions/golang:1.22-alpine3.19

      - run: apk add --no-cache npm

      - run: npm install

      - run: go install github.com/google/osv-scanner/cmd/osv-scanner@v1

      - run: osv-scanner --json . > osv-report.json
        continue-on-error: true

      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: safety-report
          path: osv-report.json
