name: Django

on:
  push:
    branches:
      - main

jobs:
  osv-scanner:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - run: sudo apt-get install npm
      - run: npm install
      - run: go install github.com/google/osv-scanner/cmd/osv-scanner@v1
      - run: osv-scanner --ymal . > osv-report.ymal
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        with:
          name: OSV-Report
          path: osv-report.ymal
        if: always()
