jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager

  Semgrep:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          name: Run Semgrep scan
          command: |
            /usr/local/bin/python -m pip install --upgrade pip
            pip3 install semgrep==1.30.0
            semgrep scan --config p/secrets --json --output Semgrep.json || true
            docker run --rm -v ${PWD}:/src returntocorp/semgrep semgrep --config auto --output semgrep-output.json --json || true
            mv Semgrep.json semgrep-results
            mv emgrep-output.json semgrep-results
      - store_artifacts:
          path: semgrep-results
          destination: Semgrep-artifact

  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1
          when: on_fail           # Even if the job fails, continue to the next stages

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a deploy step."

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
            - build
      - Semgrep:
          requires:
            - test
      - integration:
          requires:
            - Semgrep
      - prod:
          type: approval
          requires:
            - integration
