version: 2.1
jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check
  semgrep:
    docker:
      - image: semgrep/semgrep:latest
    steps:
      - checkout
      - run:
          name: Run Semgrep scan
          command: |
            semgrep \
              --config=semgrep-rules.yml \
              --json --output Semgrep.json \
              --metrics=off || true
      - store_artifacts:
          path: Semgrep.json
          destination: Semgrep-artifact
  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager
          
  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1
          when: on_fail                    # Even if the job fails, continue to the next stages

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a deploy step"

workflows:
  version: 2
  django:
    jobs:
      - build
      - Semgrep:
          requires:
            - build
      - test:
          requires:
            - build
      - integration:
          requires:
            - test
      - prod:
          type: approval
          requires:
            - integration
