version: 2.1

jobs:
  build:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Install & Check
          command: |
            pip install -r requirements.txt
            python manage.py check

  semgrep:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          name: Run Semgrep scan
          command: |
            /usr/local/bin/python -m pip install --upgrade pip
            pip3 install semgrep==1.30.0
            semgrep scan --config p/secrets --json --output Semgrep.json || true
      - store_artifacts:
          path: Semgrep.json
          destination: Semgrep-artifact

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Install & Test
          command: |
            pip install -r requirements.txt
            python manage.py test taskManager

  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Integration step (allowed to fail)
          command: |
            echo "This is an integration step"
            exit 1

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Deploy
          command: echo "This is a deploy step"

workflows:
  version: 2
  django:
    jobs:
      - build
      - semgrep:
          requires:
            - build
      - test:
          requires:
            - build
      - integration:
          requires:
            - test
      - prod:
          type: approval
          requires:
            - integration
