jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo "This is a build step"

  test:
    machine: true
    steps:
      - checkout
      - run: echo "This is a test step"

    
  odc-backend:
    machine: true
    steps:
      - checkout
      - run: chmod +x ./run-depcheck.sh && ./run-depcheck.sh || true

      - store_artifacts:
          path: reports/dependency-check-report.json
          destination: depcheck-artifact

workflows:
  version: 2
  django:
    jobs:
      - build
      - test
      - odc-backend
