name: Django

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - run: |
          pip3 install --upgrade virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py check

  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - run: |
          pip3 install --upgrade virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py test taskManager

  osv-scanner:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4  # ✅ Fixed: Uses setup-go instead of invalid reference
        with:
          go-version: '1.22'
      - run: sudo apt-get install npm  # For Ubuntu (Alpine uses `apk add npm`)
      - run: npm install
      - run: go install github.com/google/osv-scanner/cmd/osv-scanner@v1
      - run: osv-scanner --json . > osv-report.json
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        with:
          name: OSV-Report
          path: osv-report.json
        if: always()  # Uploads the artifact even if the job fails

  integration:
    runs-on: ubuntu-22.04
    needs: osv-scanner
    steps:
      - run: echo "This is an integration step"
      - run: exit 1
        continue-on-error: true

  prod:
    runs-on: ubuntu-22.04
    needs: integration
    steps:
      - run: echo "This is a deploy step."
