name: Django Security Scan

on:
  push:
    branches: [ main ]

jobs:
  git_secrets:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run git_secrets Scanner
        run: docker run --rm -v $(pwd):/src -i hysnsec/trufflehog  filesystem /src --json | tee secrets.json
        continue-on-error: true
        
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path:
            secrets.json
        if: always()
