name: Django Security Scan

on:
  push:
    branches: [ main ]

jobs:
  bandit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run detect-secrets Scanner
        run: |
            docker pull hysnsec/bandit
            docker run --rm -v $(pwd):/src hysnsec/bandit -r /src -f json | tee bandit.json
        continue-on-error: true
        
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path:
            bandit.json
        if: always()
