name: Django

on:
  push:
    branches:
      - main

jobs:
  # First define the test job that osv-scanner depends on
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          pip3 install --upgrade virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py test taskManager

  # Then define the osv-scanner job
  osv-scanner:
    runs-on: ubuntu-22.04
    needs: test  # This now correctly references the test job above
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - run: sudo apt-get install npm
      - run: npm install
      - run: go install github.com/google/osv-scanner/cmd/osv-scanner@v1
      - run: osv-scanner --ymal . > osv-report.ymal
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        with:
          name: OSV-Report
          path: osv-report.ymal
        if: always()
