name: Django Security Scan

on:
  push:
    branches: [ main ]

jobs:
  semgrep:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run detect-secrets Scanner
        run: docker run --rm -v ${PWD}:/src returntocorp/semgrep semgrep --config auto --output semgrep-output.json --json
        continue-on-error: true
    
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path:
            semgrep-output.json
        if: always()
