name: Django Security Scan

on:
  push:
    branches: [ main ]

jobs:
  detect-secrets:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run detect-secrets Scanner
        run: docker pull hysnsec/detect-secrets
        run: docker run -it -v $(pwd):/src -w /src hysnsec/detect-secrets --json | tee secrets.json
        continue-on-error: true
        
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path:
            secrets.json
        if: always()
