name: Django                                  # workflow name

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.6'

      - run: |
          pip3 install --upgrade virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py check

  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - run: |
          pip3 install --upgrade virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py test taskManager

  oast:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v2

      - run: pip3 install pip-audit==1.1.2
      - run: pip-audit -r ./requirements.txt -f json | tee pip-audit-output.json
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        with:
          name: pip-audit
          path: pip-audit-output.json
        if: always()

  integration:
    runs-on: ubuntu-22.04
    needs: oast
    steps:
      - run: echo "This is an integration step"
      - run: exit 1
        continue-on-error: true

  prod:
    runs-on: ubuntu-22.04
    needs: integration
    steps:
      - run: echo "This is a deploy step."
